GET http://localhost:8080/posts

###

POST http://localhost:8080/posts
Content-Type: application/json

{
        "userId":   "asdfadsfdsfadsf",
        "location": "1234",
        "category": "adf",
        "title":    "adsf",
        "upvotes":  12,
        "comments": "asdf"
}