# Custom REST API testing script, using the REST Client extension for VS Code

GET http://localhost:8080/posts

###

GET http://localhost:8080/posts/byId/669c6aaa7d4f8a805cc6c6a2

###

GET http://localhost:8080/posts/feed?lat=40.5798912&long=-80.0653312&maxDistance=10000000000&limit=10&offset=0

###

PATCH http://localhost:8080/posts/byId/669c6236fb719ce1dfc9d9b9?addOrRemoveUpvote=REMOVE
Content-Type: application/json

{
    "upvotes": 12,
    "usersWhoUpvoted": "b"
}

###

DELETE http://localhost:8080/posts/byId/668cd9362fe55d0301877751

###

POST http://localhost:8080/posts
Content-Type: application/json

{
    "userId":   "asdfadsfdsfadsf",
    "location": {
        "type": "Point",
        "lat": 40, 
        "long": 10
    },
    "category": "adf",
    "title":    "adsf",
    "upvotes":  6,
    "comments": ["asdf"],
    "usersWhoUpvoted": ["asdf"],
    "usersWhoDownvoted": ["1234"]
}

###

GET http://localhost:8080/comments

###

GET http://localhost:8080/comments/forPost
Content-Type: application/json

{
    "commentIds": ["66a31a75dbbb8dd2a05a5116", "66a3210edf5290d5eecd0e6d"]
}

###

POST http://localhost:8080/comments
Content-Type: application/json

{
    "userId": "testing",
    "commentContent": "NEW COMMENTFRFR",
    "upvotes": 1,
    "usersWhoUpvoted": "testing",
    "usersWhoDownvoted": 0
}