# Custom REST API testing script, using the REST Client extension for VS Code

GET http://localhost:8080/posts

###

GET http://localhost:8080/posts/byId/669b421d7ff48522323cfa96

###

GET http://localhost:8080/posts/feed?lat=40.5798912&long=-80.0653312&maxDistance=10000000000&limit=10&offset=0

###

PATCH http://localhost:8080/posts/byId/669c6236fb719ce1dfc9d9b9?addOrRemoveUpvote=REMOVE
Content-Type: application/json

{
    "upvotes": 12,
    "usersWhoUpvoted": "b"
}

###

DELETE http://localhost:8080/posts/byId/668cd9362fe55d0301877751

###

POST http://localhost:8080/posts
Content-Type: application/json

{
        "userId":   "asdfadsfdsfadsf",
        "location": {
            "type": "Point",
            "lat": 40, 
            "long": 10
        },
        "category": "adf",
        "title":    "adsf",
        "upvotes":  6,
        "comments": ["asdf"],
        "usersWhoUpvoted": ["asdf"],
        "usersWhoDownvoted": ["1234"]
}